In [18]:
'''
Overview
this notebook parses all past ufc fight stats when run, it does not include upcoming fights


scrape ufc fight stats
get all event details, name, url, date, location for all ufc events
for each event, get fight details all fights on card
parse each fight to get fight stats of both fighters
'''

'\nOverview\nthis notebook parses all past ufc fight stats when run, it does not include upcoming fights\n\n\nscrape ufc fight stats\nget all event details, name, url, date, location for all ufc events\nfor each event, get fight details all fights on card\nparse each fight to get fight stats of both fighters\n'

In [2]:
# imports
import time, pandas as pd
from tqdm.notebook import tqdm_notebook

# import library
import scrape_ufc_stats_library as LIB

# import config
import yaml
config = yaml.safe_load(open('scrape_ufc_stats_config.yaml'))

# Parse Event Details
Includes:
<br>
Event
<br>
URL
<br>
Date
<br>
Location
<br>

In [3]:
# define url to parse
events_url = config['completed_events_all_url']

In [4]:
# get soup
soup = LIB.get_soup(events_url)

# parse event details
all_event_details_df = LIB.parse_event_details(soup)

# show event details
display(all_event_details_df)

# write event details to file
print(config['event_details_file_name'])
all_event_details_df.to_csv(config['event_details_file_name'], index=False)

,EVENT,URL,DATE,LOCATION
0,UFC Fight Night: Dolidze vs. Hernandez,http://ufcstats.com/event-details/6cd3dfc54f01...,"August 09, 2025","Las Vegas, Nevada, USA"
1,UFC Fight Night: Taira vs. Park,http://ufcstats.com/event-details/f2c934689243...,"August 02, 2025","Las Vegas, Nevada, USA"
2,UFC Fight Night: Whittaker vs. De Ridder,http://ufcstats.com/event-details/28d8638ea0a7...,"July 26, 2025","Abu Dhabi, Abu Dhabi, United Arab Emirates"
3,UFC 318: Holloway vs. Poirier 3,http://ufcstats.com/event-details/b8e2f10efb6e...,"July 19, 2025","New Orleans, Louisiana, USA"
4,UFC Fight Night: Lewis vs. Teixeira,http://ufcstats.com/event-details/7b03d9df5910...,"July 12, 2025","Nashville, Tennessee, USA"
...,...,...,...,...
737,UFC 6: Clash of the Titans,http://ufcstats.com/event-details/1c3f5e85b59e...,"July 14, 1995","Casper, Wyoming, USA"
738,UFC 5: The Return of the Beast,http://ufcstats.com/event-details/dedc3bb440d0...,"April 07, 1995","Charlotte, North Carolina, USA"
739,UFC 4: Revenge of the Warriors,http://ufcstats.com/event-details/b60391da771d...,"December 16, 1994","Tulsa, Oklahoma, USA"
740,UFC 3: The American Dream,http://ufcstats.com/event-details/1a49e0670dfa...,"September 09, 1994","Charlotte, North Carolina, USA"
741,UFC 2: No Way Out,http://ufcstats.com/event-details/a6a9ab5a824e...,"March 11, 1994","Denver, Colorado, USA"

../data/ufc_event_details.csv

In [5]:
from pathlib import Path

csv_path = Path(config['event_details_file_name'])

df = pd.read_csv(csv_path)

event_id = df["URL"].astype(str).str.rstrip("/").str.split("/").str[-1]

df.insert(0, "EVENT_ID", event_id)

df.to_csv(csv_path, index=False)

print("Rows:", len(df))
display(df.head(5))

Rows: 742

,EVENT_ID,EVENT,URL,DATE,LOCATION
0,6cd3dfc54f01287f,UFC Fight Night: Dolidze vs. Hernandez,http://ufcstats.com/event-details/6cd3dfc54f01...,"August 09, 2025","Las Vegas, Nevada, USA"
1,f2c934689243fe4e,UFC Fight Night: Taira vs. Park,http://ufcstats.com/event-details/f2c934689243...,"August 02, 2025","Las Vegas, Nevada, USA"
2,28d8638ea0a71908,UFC Fight Night: Whittaker vs. De Ridder,http://ufcstats.com/event-details/28d8638ea0a7...,"July 26, 2025","Abu Dhabi, Abu Dhabi, United Arab Emirates"
3,b8e2f10efb6eca85,UFC 318: Holloway vs. Poirier 3,http://ufcstats.com/event-details/b8e2f10efb6e...,"July 19, 2025","New Orleans, Louisiana, USA"
4,7b03d9df5910917d,UFC Fight Night: Lewis vs. Teixeira,http://ufcstats.com/event-details/7b03d9df5910...,"July 12, 2025","Nashville, Tennessee, USA"

# Parse Fight Details
Includes:
<br>
Event
<br>
Bout
<br>
URL

In [6]:
# define list of urls of fights to parse
list_of_events_urls = list(all_event_details_df['URL'])

In [7]:
# create empty df to store fight details
all_fight_details_df = pd.DataFrame(columns=config['fight_details_column_names'])

# loop through each event and parse fight details
for url in tqdm_notebook(list_of_events_urls):

    # get soup
    soup = LIB.get_soup(url)

    # parse fight links
    fight_details_df = LIB.parse_fight_details(soup)
    
    # concat fight details
    all_fight_details_df = pd.concat([all_fight_details_df, fight_details_df])

# show all fight details
display(all_fight_details_df)

# write fight details to file
all_fight_details_df.to_csv(config['fight_details_file_name'], index=False)

  0%|          | 0/742 [00:00<?, ?it/s]

,EVENT,BOUT,URL
0,UFC Fight Night: Dolidze vs. Hernandez,Anthony Hernandez vs. Roman Dolidze,http://ufcstats.com/fight-details/68fe62bac7fd...
1,UFC Fight Night: Dolidze vs. Hernandez,Steve Erceg vs. Ode Osbourne,http://ufcstats.com/fight-details/37d58369782c...
2,UFC Fight Night: Dolidze vs. Hernandez,Iasmin Lucindo vs. Angela Hill,http://ufcstats.com/fight-details/646c79a7ecd1...
3,UFC Fight Night: Dolidze vs. Hernandez,Andre Fili vs. Christian Rodriguez,http://ufcstats.com/fight-details/98d6771af9b0...
4,UFC Fight Night: Dolidze vs. Hernandez,Jean Matsumoto vs. Miles Johns,http://ufcstats.com/fight-details/ed5383b50ffc...
...,...,...,...
10,UFC 2: No Way Out,Orlando Wiet vs. Robert Lucarelli,http://ufcstats.com/fight-details/3b020d4914b4...
11,UFC 2: No Way Out,Frank Hamaker vs. Thaddeus Luster,http://ufcstats.com/fight-details/d917c8c7461b...
12,UFC 2: No Way Out,Johnny Rhodes vs. David Levicki,http://ufcstats.com/fight-details/ccee020be2e8...
13,UFC 2: No Way Out,Patrick Smith vs. Ray Wizard,http://ufcstats.com/fight-details/4b9ae533ccb3...
14,UFC 2: No Way Out,Scott Morris vs. Sean Daugherty,http://ufcstats.com/fight-details/4acab67848e7...

In [8]:
csv_path = Path(config['fight_details_file_name'])
df = pd.read_csv(csv_path)

fight_id = df["URL"].astype(str).str.strip().str.rstrip("/").str.split("/").str[-1]

df["FIGHT_ID"] = fight_id

if "EVENT_ID" in df.columns:
    df = df.drop(columns=["EVENT_ID"])

preferred = ["FIGHT_ID", "EVENT", "BOUT", "URL"]
df = df[[c for c in preferred if c in df.columns] + [c for c in df.columns if c not in preferred]]

df.to_csv(csv_path, index=False)

print(f"✅ Updated file: {csv_path} | Rows: {len(df)}")
display(df.head(5))

✅ Updated file: ../data/ufc_fight_details.csv | Rows: 8300

,FIGHT_ID,EVENT,BOUT,URL
0,68fe62bac7fd8bb0,UFC Fight Night: Dolidze vs. Hernandez,Anthony Hernandez vs. Roman Dolidze,http://ufcstats.com/fight-details/68fe62bac7fd...
1,37d58369782cb86b,UFC Fight Night: Dolidze vs. Hernandez,Steve Erceg vs. Ode Osbourne,http://ufcstats.com/fight-details/37d58369782c...
2,646c79a7ecd12e5f,UFC Fight Night: Dolidze vs. Hernandez,Iasmin Lucindo vs. Angela Hill,http://ufcstats.com/fight-details/646c79a7ecd1...
3,98d6771af9b0ebe5,UFC Fight Night: Dolidze vs. Hernandez,Andre Fili vs. Christian Rodriguez,http://ufcstats.com/fight-details/98d6771af9b0...
4,ed5383b50ffcdded,UFC Fight Night: Dolidze vs. Hernandez,Jean Matsumoto vs. Miles Johns,http://ufcstats.com/fight-details/ed5383b50ffc...

# Parse Fight Results and Fight Stats

Fight Results Includes:
<br>
Event
<br>
Bout
<br>
Weightclass
<br>
Method
<br>
Round
<br>
Time
<br>
Time Format
<br>
Referee
<br>
Details
<br>

Fight Stats Includes:
<br>
Event
<br>
Bout
<br>
Round
<br>
Fighter
<br>
Kd
<br>
Sig.Str.
<br>
Sig.Str. %
<br>
Total Str.
<br>
Td
<br>
Td %
<br>
Sub.Att
<br>
Rev.
<br>
Ctrl
<br>
Head
<br>
Body
<br>
Leg
<br>
Distance
<br>
Clinch
<br>
Ground
<br>

In [9]:
# define list of urls of fights to parse
list_of_fight_details_urls = list(all_fight_details_df['URL'])

## Optional cell for running
Only run this cell if you want to redo checkpoint, firght results and fight stats

In [ ]:
# File paths
results_path = Path(config["fight_results_file_name"])
stats_path   = Path(config["fight_stats_file_name"])
ckpt_path    = Path("processed_fight_urls.ckpt")

# Make sure folders exist
results_path.parent.mkdir(parents=True, exist_ok=True)
stats_path.parent.mkdir(parents=True, exist_ok=True)

# Reset CSVs to header-only
pd.DataFrame(columns=config["fight_results_column_names"]).to_csv(results_path, index=False)
pd.DataFrame(columns=config["fight_stats_column_names"]).to_csv(stats_path, index=False)

# Remove checkpoint
ckpt_path.unlink(missing_ok=True)

print(f"✅ Cleared (header only): {results_path}")
print(f"✅ Cleared (header only): {stats_path}")
print(f"✅ Deleted checkpoint (if existed): {ckpt_path}")

✅ Cleared (header only): ../data/ufc_fight_results.csv
✅ Cleared (header only): ../data/ufc_fight_stats.csv
✅ Deleted checkpoint (if existed): ../data/processed_fight_urls.ckpt

In [11]:
import time
# --- create empty dfs just for display (optional)
all_fight_results_df = pd.DataFrame(columns=config['fight_results_column_names'])
all_fight_stats_df   = pd.DataFrame(columns=config['fight_stats_column_names'])

ckpt_path = Path("processed_fight_urls.ckpt")

# Load checkpoint
done = set()
if ckpt_path.exists():
    done = set(line.strip() for line in ckpt_path.read_text().splitlines() if line.strip())

# Filter out already processed
todo = [u for u in list_of_fight_details_urls if u not in done]

# For a 10-URL test, uncomment:
# todo = todo[:10]

print(f"To process now: {len(todo)} | Already done: {len(done)}")

def append_csv(df: pd.DataFrame, path: str, columns: list):
    """Append rows to CSV with consistent schema; write header only if new."""
    if df is None or df.empty:
        return
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    header = not p.exists() or p.stat().st_size == 0
    df.reindex(columns=columns).to_csv(p, mode="a", header=header, index=False)

fail_log = []

# loop through each fight and parse fight results and stats
for url in tqdm_notebook(todo):
    try:
        # get soup
        soup = LIB.get_soup(url)

        # parse fight results and fight stats
        fight_results_df, fight_stats_df = LIB.parse_organise_fight_results_and_stats(
            soup,
            url,
            config['fight_results_column_names'],
            config['totals_column_names'],
            config['significant_strikes_column_names']
        )

        # append to disk immediately (so you never lose more than one URL)
        append_csv(fight_results_df, config['fight_results_file_name'], config['fight_results_column_names'])
        append_csv(fight_stats_df,   config['fight_stats_file_name'],   config['fight_stats_column_names'])

        # also keep small in-memory copies just for display (optional)
        all_fight_results_df = pd.concat([all_fight_results_df, fight_results_df], ignore_index=True)
        all_fight_stats_df   = pd.concat([all_fight_stats_df,   fight_stats_df],   ignore_index=True)

        # mark checkpoint only after successful writes
        with open(ckpt_path, "a") as f:
            f.write(url + "\n")

        # polite delay to avoid hammering the site
        time.sleep(0.4)

    except Exception as e:
        print(f"⚠️ Failed: {url} -> {e}")
        fail_log.append({"URL": url, "ERROR": str(e)})
        time.sleep(1.0)
        continue

# show samples (avoid rendering thousands of rows)
display(all_fight_results_df.head(10))
display(all_fight_stats_df.head(10))

print(f"Done. Success: {len(todo) - len(fail_log)} | Failed: {len(fail_log)}")

# OPTIONAL: persist a fail log
if fail_log:
    fail_df = pd.DataFrame(fail_log)
    fail_path = Path(config["fight_stats_file_name"]).with_name("failed_fights.csv")
    if fail_path.exists():
        prev = pd.read_csv(fail_path)
        fail_df = pd.concat([prev, fail_df], ignore_index=True).drop_duplicates(subset=["URL"], keep="last")
    fail_df.to_csv(fail_path, index=False)
    print(f"⚠️ Fail log written -> {fail_path}")

To process now: 0 | Already done: 8300

0it [00:00, ?it/s]

Empty DataFrame
Columns: [EVENT, BOUT, OUTCOME, WEIGHTCLASS, METHOD, ROUND, TIME, TIME FORMAT, REFEREE, DETAILS, URL]
Index: []

Empty DataFrame
Columns: [EVENT, BOUT, ROUND, FIGHTER, KD, SIG.STR., SIG.STR. %, TOTAL STR., TD, TD %, SUB.ATT, REV., CTRL, HEAD, BODY, LEG, DISTANCE, CLINCH, GROUND]
Index: []

Done. Success: 0 | Failed: 0

In [17]:
from pathlib import Path
from IPython.display import display

results_path = Path(config['fight_results_file_name'])
stats_path   = Path(config['fight_stats_file_name'])

def norm_text(s: pd.Series) -> pd.Series:
    s = s.astype(str).fillna("")
    s = s.str.replace(r"\s+", " ", regex=True).str.strip()
    s = s.str.replace(r"\s+vs\.\s+", " vs. ", regex=True)
    return s

def id_from_url(s: pd.Series) -> pd.Series:
    return s.astype(str).str.strip().str.rstrip("/").str.split("/").str[-1]

def normalize_fight_id_col(df: pd.DataFrame) -> pd.DataFrame:
    # Rename any case variant (fight_id, Fight_id, etc.) to FIGHT_ID
    for c in list(df.columns):
        if c.lower() == "fight_id" and c != "FIGHT_ID":
            df = df.rename(columns={c: "FIGHT_ID"})
            break
    return df

# --- 1) RESULTS: ensure FIGHT_ID from URL (read as str to avoid dtype warnings)
res = pd.read_csv(results_path, dtype=str)
res = normalize_fight_id_col(res)
res["FIGHT_ID"] = id_from_url(res["URL"])
res = res[["FIGHT_ID"] + [c for c in res.columns if c != "FIGHT_ID"]]
res.to_csv(results_path, index=False)
print(f"✅ Updated results with FIGHT_ID -> {results_path} (rows: {len(res)})")

# Build mapping (EVENT,BOUT) -> FIGHT_ID
map_df = res[["EVENT", "BOUT", "FIGHT_ID"]].copy()
map_df["EVENT_JOIN"] = norm_text(map_df["EVENT"])
map_df["BOUT_JOIN"]  = norm_text(map_df["BOUT"])
map_df = map_df.drop_duplicates(subset=["EVENT_JOIN", "BOUT_JOIN"])

# --- 2) STATS: add/overwrite FIGHT_ID via join
st = pd.read_csv(stats_path, dtype=str)
st = normalize_fight_id_col(st)

st["EVENT_JOIN"] = norm_text(st["EVENT"])
st["BOUT_JOIN"]  = norm_text(st["BOUT"])

# Merge mapping as FIGHT_ID_MAP to avoid suffix chaos
right = map_df[["EVENT_JOIN", "BOUT_JOIN", "FIGHT_ID"]].rename(columns={"FIGHT_ID": "FIGHT_ID_MAP"})
st = st.merge(right, on=["EVENT_JOIN", "BOUT_JOIN"], how="left", validate="many_to_one")

# Coalesce: keep existing FIGHT_ID if present, else take mapped one
if "FIGHT_ID" in st.columns:
    st["FIGHT_ID"] = st["FIGHT_ID"].where(st["FIGHT_ID"].notna() & (st["FIGHT_ID"].str.strip() != ""), st["FIGHT_ID_MAP"])
else:
    st["FIGHT_ID"] = st["FIGHT_ID_MAP"]

# Report misses (no id found from mapping)
missing = int(st["FIGHT_ID"].isna().sum())
if missing:
    print(f"⚠️ Could not assign FIGHT_ID to {missing} stat rows. A few unmatched (EVENT,BOUT):")
    display(st.loc[st["FIGHT_ID"].isna(), ["EVENT","BOUT"]].drop_duplicates().head(10))

# Reorder and drop helpers
st = st[["FIGHT_ID"] + [c for c in st.columns if c not in {"FIGHT_ID","EVENT_JOIN","BOUT_JOIN","FIGHT_ID_MAP"}]]

st.to_csv(stats_path, index=False)
print(f"✅ Updated stats with FIGHT_ID -> {stats_path} (rows: {len(st)})")

✅ Updated results with FIGHT_ID -> ../data/ufc_fight_results.csv (rows: 8300)
✅ Updated stats with FIGHT_ID -> ../data/ufc_fight_stats.csv (rows: 39110)